parameters:
  - name: Nightly
    default: true

jobs:
  - job: SmokeTest
    condition: or(eq(${{ parameters.Nightly }}, true), eq(variables['RunSmokeTests'], 'true'))
    strategy:
      matrix:
        Linux (AzureCloud):
          OSVmImage: "ubuntu-18.04"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
        Linux (AzureCloud Canary):
          OSVmImage: "ubuntu-18.04"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources-preview)
          ArmTemplateParameters: $(azureCloudArmParameters)
          Location: "eastus2euap"
        Windows_NetCoreApp (AzureCloud):
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
        Windows_NetFramework (AzureCloud):
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
        MacOs (AzureCloud):
          OSVmImage: "macOS-10.15"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ArmTemplateParameters: $(azureCloudArmParameters)
        Windows_NetCoreApp (AzureUSGovernment):
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
        Windows_NetFramework (AzureUSGovernment):
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
        Windows_NetCoreApp (AzureChinaCloud):
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
        Windows_NetFramework (AzureChinaCloud):
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          ArmTemplateParameters: $(azureChinaCloudArmParameters)

    pool:
      vmImage: $(OSVmImage)

    variables:
      azureCloudArmParameters: "@{ storageEndpointSuffix = 'core.windows.net'; azureCloud = 'AzureCloud'; }"
      azureUSGovernmentArmParameters: "@{ storageEndpointSuffix = 'core.usgovcloudapi.net'; azureCloud = 'AzureUSGovernment'; }"
      azureChinaCloudArmParameters: "@{ storageEndpointSuffix = 'core.chinacloudapi.cn'; azureCloud = 'AzureChinaCloud'; }"

    steps:
      - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml

      - task: PowerShell@2
        inputs:
          targetType: filePath
          filePath: ./common/SmokeTests/SmokeTest/Update-Dependencies.ps1
          workingDirectory: common/SmokeTests/SmokeTest
          pwsh: true
          ${{ if parameters.Nightly }}:
            arguments: -CI -Nightly
            displayName: Use latest dev feed package versions
          ${{ if not(parameters.Nightly) }}:
            arguments: -CI
            displayName: Use latest package versions

      - pwsh: Get-Content ./common/SmokeTests/SmokeTest/SmokeTest.csproj
        displayName: Show SmokeTest.csproj

      - template: /eng/pipelines/templates/steps/install-dotnet.yml

      - pwsh: dotnet restore ./common/SmokeTests/SmokeTest/SmokeTest.csproj
        displayName: dotnet restore

      - template: /eng/common/TestResources/deploy-test-resources.yml
        parameters:
          ServiceDirectory: '$(Build.SourcesDirectory)/common/SmokeTests/'
          SubscriptionConfiguration: $(SubscriptionConfiguration)
          ArmTemplateParameters: $(ArmTemplateParameters)

      - pwsh: dotnet run -p .\common\SmokeTests\SmokeTest\SmokeTest.csproj --framework $(TestTargetFramework)
        displayName: "Run Smoke Tests"

      - template: /eng/common/TestResources/remove-test-resources.yml
        parameters:
          ServiceDirectory: '$(Build.SourcesDirectory)/common/SmokeTests/'
          SubscriptionConfiguration: $(SubscriptionConfiguration)
