parameters:
  Artifacts: []
  TestPipeline: false
  ArtifactName: 'not-specified'
  # Publish to https://dev.azure.com/azure-sdk/public/_packaging?_a=feed&feed=azure-sdk-for-net
  DevOpsFeedId: '29ec6040-b234-4e31-b139-33dc4287b756/fa8c16a3-dbe0-4de2-a297-03065ec1ba3f'

stages:
  - ${{if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'))}}:
    - stage: SmokeTest_Release_Packages
      displayName: Smoke Test Release Packages
      jobs:
        # pipelines only supports template each when it generates the entire script block.
        - ${{ each artifact in parameters.Artifacts }}:
          - template: /eng/pipelines/templates/steps/check-smoke-test.yml
            parameters:
              package: ${{ artifact.name }}
        - template: /eng/pipelines/templates/jobs/smoke-tests.yml
          condition: eq(variables['RunSmokeTests'], 'true')
          parameters:
            Nightly: false
